### ISSUE TITLE
Improvements to copy button

### ISSUE THREAD

**Issue by sean0x42** [ducthienbui97/gitlicense#13]
Currently the copy button could be a little better. Some suggestions:

- [ ] Add some kind of indication that the textarea's contents has been copied to your clipboard. Either a tooltip or a toast message.
- [x] Make the button look like it's a part of the textarea. Remove whitespace between them and fix border radius.

Any other ideas are appreciated.

**Comment by ducthienbui97** [comment]
@LuckehPickle  Thank you for the suggestions.
@quangIO What do you think? You contributed the copy button.

**Comment by ducthienbui97** [comment]
btw, the icon notice is actually about website's favicon not copy or search icon.

**Comment by quangIO** [comment]
For the sake of consistency. I believe the current icon (using font awesome) is fine. Can you make it display a tooltip or toaster ?

**Comment by LuckehPickle** [comment]
@quangIO Yea, I agree. I'll update the description. Also toast is the exactly the word I was looking for, thanks!

**Comment by Flippylosaurus** [comment]
I'm on it.

**Comment by Flippylosaurus** [comment]
#20

**Comment by LuckehPickle** [comment]
I'm going to try implementing a JQuery/Toastr free solution. I feel like it's overkill to add two libraries just so we can have a single toast.

**Comment by ducthienbui97** [comment]
How about bootstrap tooltips?

**Comment by LuckehPickle** [comment]
@ducthienbui97 I feel like that could definitely work. Tooltips may be a better solution compared to toasts since they're right on the button that you're clicking. I'm not familiar with bootstrap though, so someone else will have to implement it.

**Comment by Janatbek** [comment]
I can do it with Bootstrap

**Comment by ducthienbui97** [comment]
@Janatbek  give it a try

Another solution is using [Tippyjs](https://atomiks.github.io/tippyjs/)  or [Tooltipjs](https://popper.js.org/tooltip-examples.html)
