### ISSUE TITLE
Fix additional space characters in the textarea of Markdown and HTML

### ISSUE THREAD

**Issue by ducthienbui97** [ducthienbui97/gitlicense#14]
Currently, there are some addtional space characters the textarea of Markdown and HTML (image below). The textarea of RST is already be fixed. You can follow that.
The file needs to be fixed is [template.html](https://github.com/ducthienbui97/gitlicense/blob/4b6d850382067bacb26685546090f30c6b5a59e6/public/pages/template.html)
![image](https://user-images.githubusercontent.com/10867758/31063714-2ebf6220-a781-11e7-939a-7f7a9df113b1.png)

**Comment by scrabill** [comment]
I'd like to give this a try.

**Comment by Adroit11** [comment]
Would like to roll in on this

**Comment by ducthienbui97** [comment]
@scrabill  @Adroit11  Check the [contributing file](https://github.com/ducthienbui97/gitlicense/blob/master/CONTRIBUTING.md) for more information of contribute process. Remember, it's not first in first serve process, feel free to open a PR about this issue as long as this issue is opened even if someone opened a PR before you. The best PR is chosen not the first one.
