### ISSUE TITLE
Error messages when repository doesn't exist.

### ISSUE THREAD

**Issue by sean0x42** [ducthienbui97/gitlicense#21]
At the moment, nothing happens when you enter a repo that doesn't exist. We should have a toast notification that says something along the lines of: "This repository could not be found."

**Comment by ducthienbui97** [comment]
The solution may be to use [yar](https://github.com/hapijs/yar) to save error message before redirect to home page. And modify [layout](https://github.com/ducthienbui97/gitlicense/blob/master/public/layout/default.html) to display error if there is.

**Comment by darshkpatel** [comment]
@ducthienbui97 
If we're using jQuery in #20 then we could call the GitHub Page and see if we get GitHub's 404 page and show a tooltip on the home page.

**Comment by ducthienbui97** [comment]
@darshkpatel  querying github in the front end to check if the repo exist or not is a good choice, however jQuery may be too big if you just need to use for api call. I would recommend using [axios](https://github.com/axios/axios) as I use it all the time.
