### ISSUE TITLE
Add color for users to choose

### ISSUE THREAD

**Issue by ducthienbui97** [ducthienbui97/gitlicense#24]
Do you know you can choose the color of badges?
For example
``` md
[![GitLicense](https://gitlicense.com/badge/ducthienbui97/gitlicense?color=red)](https://gitlicense.com/license/ducthienbui97/gitlicense)
```
[![GitLicense](https://gitlicense.com/badge/ducthienbui97/gitlicense?color=red)](https://gitlicense.com/license/ducthienbui97/gitlicense)

or

``` md
[![GitLicense](https://gitlicense.com/badge/ducthienbui97/gitlicense?color=yellow)](https://gitlicense.com/license/ducthienbui97/gitlicense)
```

[![GitLicense](https://gitlicense.com/badge/ducthienbui97/gitlicense?color=yellow)](https://gitlicense.com/license/ducthienbui97/gitlicense)

There are a few colors to be chosen: brightgreen, green, yellow, yellowgreen, orange, red, blue, grey, lightgrey

Try to add a dropbox for user to choose color and edit value in textareas accordingly

**Comment by hmelenok** [comment]
Hey please check it out https://github.com/ducthienbui97/gitlicense/pull/26
